#!/usr/bin/env python3
"""
Extract prompts and parameters from PNG files generated by SwarmUI.
"""
import sys
import struct
import json

def read_png_metadata(filename):
    """Read tEXt chunks from PNG file."""
    metadata = {}

    with open(filename, 'rb') as f:
        # Verify PNG signature
        signature = f.read(8)
        if signature != b'\x89PNG\r\n\x1a\n':
            print(f"❌ {filename} is not a PNG file")
            return None

        # Read chunks
        while True:
            try:
                # Chunk length
                length_data = f.read(4)
                if len(length_data) < 4:
                    break
                length = struct.unpack('>I', length_data)[0]

                # Chunk type
                chunk_type = f.read(4).decode('ascii')

                # Chunk data
                chunk_data = f.read(length)

                # CRC (skip)
                f.read(4)

                # If this is a tEXt chunk - read metadata
                if chunk_type == 'tEXt':
                    # tEXt format: keyword\0text
                    null_pos = chunk_data.find(b'\x00')
                    if null_pos != -1:
                        keyword = chunk_data[:null_pos].decode('latin-1')
                        text = chunk_data[null_pos+1:].decode('utf-8', errors='ignore')
                        metadata[keyword] = text

                # IEND marks end of file
                if chunk_type == 'IEND':
                    break

            except Exception as e:
                break

    return metadata

def print_metadata(filename):
    """Print metadata in human-readable format."""
    print(f"\n{'='*70}")
    print(f"📄 {filename}")
    print(f"{'='*70}")

    metadata = read_png_metadata(filename)

    if not metadata:
        print("⚠️  No metadata found")
        return

    # Parse parameters (JSON)
    if 'parameters' in metadata:
        try:
            data = json.loads(metadata['parameters'])

            # SwarmUI stores parameters in sui_image_params
            params = data.get('sui_image_params', data)
            extra = data.get('sui_extra_data', {})

            print("\n✨ PROMPT:")
            print(f"   {params.get('prompt', 'N/A')}")

            if params.get('negativeprompt'):
                print("\n🚫 NEGATIVE PROMPT:")
                print(f"   {params['negativeprompt']}")

            print("\n⚙️  PARAMETERS:")
            print(f"   Model:       {params.get('model', 'N/A')}")
            print(f"   Seed:        {params.get('seed', 'N/A')}")
            print(f"   Steps:       {params.get('steps', 'N/A')}")
            print(f"   CFG Scale:   {params.get('cfgscale', 'N/A')}")
            print(f"   Sampler:     {params.get('sampler', 'N/A')}")
            print(f"   Size:        {params.get('width', 'N/A')}×{params.get('height', 'N/A')}")

            if extra:
                print("\n⏱️  STATISTICS:")
                print(f"   Date:        {extra.get('date', 'N/A')}")
                print(f"   Preparation: {extra.get('prep_time', 'N/A')}")
                print(f"   Generation:  {extra.get('generation_time', 'N/A')}")

        except json.JSONDecodeError:
            print("\n📝 RAW PARAMETERS:")
            print(metadata['parameters'])

    # Other metadata
    other_keys = [k for k in metadata.keys() if k != 'parameters']
    if other_keys:
        print("\n📊 OTHER METADATA:")
        for key in other_keys:
            value = metadata[key]
            if len(value) > 100:
                value = value[:100] + "..."
            print(f"   {key}: {value}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 read-prompt.py <PNG file>")
        print("\nExample:")
        print("  python3 read-prompt.py output/local/raw/2026-02-01/1724001-*.png")
        sys.exit(1)

    for filename in sys.argv[1:]:
        try:
            print_metadata(filename)
        except FileNotFoundError:
            print(f"\n❌ File not found: {filename}")
        except Exception as e:
            print(f"\n❌ Error reading {filename}: {e}")
